[project]
name = 'CharitableDonation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.charitable-donation]
path = 'contracts/charitable-donation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
